# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('contactPerson', models.CharField(max_length=30)),
                ('contactNo', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('landMark', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(choices=[('IN', 'India'), ('NE', 'Nepal')], max_length=2)),
                ('state', models.CharField(choices=[('BR', 'BIHAR'), ('ND', 'NEW DELHI')], max_length=2)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('fax_no', models.IntegerField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gst_pan', models.IntegerField(null=True)),
            ],
        ),
    ]
